"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard_projects from './dashboard-projects.bones.json'
import _repo_list from './repo-list.bones.json'

configureBoneyard({"color":"#27272a","darkColor":"#27272a","animate":"shimmer"})

registerBones({
  "dashboard-projects": _dashboard_projects,
  "repo-list": _repo_list,
})
